Repository openstack-k8s-operators/glance-operator, pull requests merged in 2023-01, with the labels that each got.

#95 add service db finalizer logic
  controllers/glance_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test

#117 Use new lib-common 'PatchInstance' pattern
  api/go.mod
  api/go.sum
  controllers/glance_controller.go
  controllers/glanceapi_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#118 Clean up some removed options
  templates/glance/config/glance-api.conf
Labels: approved, lgtm, ok-to-test

#119 Add missing svc config cond for Glance CRs
  controllers/glance_controller.go
Labels: approved, lgtm

#120 Use internal endpoint to interact with Keystone
  controllers/glanceapi_controller.go
  templates/glance/config/glance-api.conf
Labels: approved, lgtm, needs-ok-to-test

#121 Set KeystoneAuthURL according to the instance type
  controllers/glance_controller.go
  controllers/glanceapi_controller.go
  templates/glance/config/glance-api.conf
Labels: approved, lgtm

#128 Enable image import plugins
  templates/glance/config/glance-api-config.json
  templates/glance/config/glance-image-import.conf
Labels: approved, lgtm

#132 Add pre-commit config
  .github/create_bundle.sh
  .github/create_opm_index.sh
  .pre-commit-config.yaml
  README.md
  api/v1beta1/conditions.go
  api/v1beta1/glance_types.go
  api/v1beta1/groupversion_info.go
  go.sum
  hack/boilerplate.go.txt
  templates/common/common.sh
  templates/glance/bin/init.sh
  templates/glance/config/policy.yaml
Labels: approved, lgtm

#136 Add renovate.json / Remove dependabot.yml
  .github/dependabot.yml
  renovate.json
Labels: approved, lgtm

#137 Upgrade to golang 1.19/SDK 1.26
  .github/workflows/build-glance-operator.yaml
  .github/workflows/golangci-lint.yaml
  Dockerfile
  Makefile
  api/bases/glance.openstack.org_glanceapis.yaml
  api/bases/glance.openstack.org_glances.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/glance.openstack.org_glanceapis.yaml
  config/crd/bases/glance.openstack.org_glances.yaml
  go.mod
Labels: approved, lgtm
