Repository openstack-k8s-operators/glance-operator, pull requests merged in 2023-07, with the labels that each got.

#266 Do not update mergo module
  renovate.json
Labels: approved, lgtm

#267 Watch RBAC resources to trigger reconcile
  controllers/glance_controller.go
Labels: approved, lgtm

#254 Cinder as GlanceAPI backend
  config/rbac/role.yaml
  controllers/glance_controller.go
  controllers/glanceapi_controller.go
  pkg/glance/dbsync.go
  pkg/glance/funcs.go
  pkg/glance/initcontainer.go
  pkg/glance/volumes.go
  pkg/glanceapi/deployment.go
Labels: approved, lgtm

#269 Watch NADs
  controllers/glanceapi_controller.go
Labels: approved, lgtm

#271 Revert "Fix CRD copy in MAkefile"
  Makefile
Labels: approved, lgtm

#272 consider global nodeSelector if not specified on the api level
  controllers/glance_controller.go
Labels: approved, lgtm

#270 Update test helper references after reorg
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/functional/glance_controller_test.go
  tests/functional/suite_test.go
Labels: approved, lgtm

#273 Check if Cinder CR exists when is set as a Glance backend
  api/go.mod
  api/go.sum
  controllers/glanceapi_controller.go
  go.mod
  go.sum
  main.go
  pkg/glance/const.go
Labels: approved, lgtm

#275 Configure renovate to pin k8s and controller-runtime for dev preview
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  renovate.json
Labels: approved

#256 Cinder backend sample
  config/samples/backends/cinder/backend.yaml
  config/samples/backends/cinder/cinder-secret.conf
  config/samples/backends/cinder/kustomization.yaml
Labels: approved, lgtm

#274 Change kuttl tests to run in arbitrary namespace
  kuttl-test.yaml
  tests/kuttl/tests/glance_scale/01-assert.yaml
  tests/kuttl/tests/glance_scale/01-deploy_glance.yaml
  tests/kuttl/tests/glance_scale/02-scale-glanceapis.yaml
  tests/kuttl/tests/glance_scale/03-scale-down-glanceapis.yaml
  tests/kuttl/tests/glance_scale/04-scale-down-zero-glanceapis.yaml
  tests/kuttl/tests/glance_scale/05-cleanup-glance.yaml
Labels: approved, lgtm, ok-to-test

#277 Use central renovate config
  renovate.json
Labels: approved, lgtm

#276 Bump lib-common and services API to v0.1.0 for dev preview
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#281 Avoid bumping own api module by renovate
  renovate.json
Labels: approved, lgtm

#282 Remove duplicate jobs from github workflow
  .github/workflows/golangci-lint.yaml
  .github/workflows/lints.yaml
Labels: approved, lgtm
